#!/bin/bash
host=$1
passfile=$2

# sync files
sshpass -p $(cat $passfile) rsync -avP --exclude=venv/ api/ $(cat $host):/home/ec2-user/ 

# login and start server
sshpass -p $(cat $passfile) ssh $(cat $host) -tt << EOF
  ./stop
  ./start
  echo "now starting server...5 sec"
  sleep 5
  exit
EOF

