#!/bin/bash
host=$1
passfile=$2

# sync files
sshpass -p $(cat $passfile) rsync -avP --exclude=venv/ api/ $(cat $host):/home/ec2-user/ 

# login to ec2 instance, install dependencies, and start server
sshpass -p $(cat $passfile) ssh $(cat $host) -tt << EOF
  ./stop
  pip3 install -r requirements.txt --user
  ./start
  echo "now starting server...5 sec"
  sleep 5
  exit
EOF

